quotes_project/quotes_app/urls.py
from django.urls import path

from .views import AuthorView, AddAuthorView, AddQuoteView, AddTagView, QuoteListView, FilterListView, BindTagView, sync

app_name = 'quotes_app'

urlpatterns = [
    path('', QuoteListView.as_view(), name='main'),
    path('add_author/', AddAuthorView.as_view(), name='add_author'),
    path('add_quote/', AddQuoteView.as_view(), name='add_quote'),
    path('add_tag/', AddTagView.as_view(), name='add_tag'),
    path('bind_tags/', BindTagView.as_view(), name='bind_tags'),
    path('tag/<str:tag>/', FilterListView.as_view(), name='tag'),
    path('author/<str:author>/', AuthorView.as_view(), name='author'),
    path('sync/', sync, name='sync'),
]

quotes_project/quotes_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes_app.urls')),
    path('users/', include('users.urls')),
]

quotes_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html',
                                     form_class=LoginForm, redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html', success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

quotes_project/quotes_app/models.py
from django.db.models import Model, CharField, ForeignKey, CASCADE, ManyToManyField


class Authors(Model):
    fullname = CharField(max_length=120)
    born_date = CharField(max_length=80)
    born_location = CharField(max_length=200)
    description = CharField()

    class Meta:
        managed = True
        db_table = 'authors'

    def __str__(self):
        return self.fullname


class Quotes(Model):
    author = ForeignKey(Authors, CASCADE, db_column='author')
    quote = CharField()
    tags = ManyToManyField('Tags', 'quotes')

    class Meta:
        managed = True
        db_table = 'quotes'

    def __str__(self):
        return self.quote


class Tags(Model):
    name = CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'tags'

    def __str__(self):
        return self.name

quotes_project/quotes_app/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea, DateField, DateInput, CheckboxSelectMultiple, \
    Select, ModelChoiceField, ModelMultipleChoiceField, SelectMultiple

from .models import Authors, Quotes, Tags


class AuthorForm(ModelForm):
    fullname = CharField(max_length=120, widget=TextInput(attrs={"class": "form-control"}))
    born_date = DateField(widget=DateInput(attrs={"class": "form-control", "placeholder": "MM/DD/YYYY"}))
    born_location = CharField(max_length=200, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(widget=Textarea(attrs={"class": "form-control"}))

    def clean_born_location(self):
        born_location = self.cleaned_data['born_location']
        return f'in {born_location}'

    class Meta:
        model = Authors
        fields = ('fullname', 'born_date', 'born_location', 'description')


class QuoteForm(ModelForm):
    quote = CharField(widget=Textarea(attrs={"class": "form-control"}))
    author = ModelChoiceField(Authors.objects.all(), widget=Select(attrs={"class": "form-select"}))
    tags = ModelMultipleChoiceField(Tags.objects.all(), widget=SelectMultiple(attrs={"class": "form-select"}),
                                    required=False)

    class Meta:
        model = Quotes
        fields = ('quote', 'author', 'tags')


class CreateTagForm(ModelForm):
    name = CharField(max_length=50, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tags
        fields = ('name',)

    def save(self, commit=True):
        tag_name = self.cleaned_data['name']
        tag, created = Tags.objects.get_or_create(name=tag_name)
        if commit:
            tag.save()
        return tag


class BindTagForm(ModelForm):
    quote = ModelChoiceField(Quotes.objects.all(), widget=Select(attrs={"class": "form-select"}), required=True)
    tags = ModelMultipleChoiceField(Tags.objects.all(), widget=SelectMultiple(attrs={"class": "form-select"}),
                                    required=True)

    class Meta:
        model = Tags
        fields = ('quote', 'tags')

    def save(self, commit=True):
        quote_instance = self.cleaned_data['quote']
        tags_instances = self.cleaned_data['tags']
        for tag_instance in tags_instances:
            if tag_instance not in quote_instance.tags.all():
                quote_instance.tags.add(tag_instance)
        if commit:
            quote_instance.save()
        return quote_instance

quotes_project/quotes_app/views.py
import requests
from bs4 import BeautifulSoup
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, F
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import View, DetailView, CreateView

from .forms import AuthorForm, QuoteForm, CreateTagForm, BindTagForm
from .models import Quotes, Authors, Tags
from .tasks import task


class BaseListView(View):
    paginate_by = 10
    template_name = 'quotes_app/quotes_list.html'

    def get(self, request, *args, **kwargs):
        tags = Tags.objects.all()
        tags_font = Tags.objects.values('name').annotate(quote_count=Count('quotes')).order_by('-quote_count', 'name')
        tags_font = tags_font.annotate(font=F('quote_count') * 2)
        paginator = Paginator(self.quotes, self.paginate_by)
        page = request.GET.get('page', 1)
        try:
            quotes = paginator.page(page)
        except PageNotAnInteger:
            quotes = paginator.page(1)
        except EmptyPage:
            quotes = paginator.page(paginator.num_pages)
        context = {'quotes': quotes, 'tags': tags, 'tags_font': tags_font, **kwargs}
        return render(request, self.template_name, context)


class QuoteListView(BaseListView):
    quotes = Quotes.objects.all().order_by('id')


class FilterListView(BaseListView):
    quotes = None

    def get(self, request, tag=None, *args, **kwargs):
        self.quotes = Quotes.objects.filter(tags__name=tag).distinct().order_by('id')
        return super().get(request, *args, **kwargs)


class AuthorView(DetailView):
    model = Authors
    template_name = 'quotes_app/author.html'
    context_object_name = 'author'
    slug_field = 'fullname'
    slug_url_kwarg = 'author'


@method_decorator(login_required, name='dispatch')
class AddAuthorView(CreateView):
    model = Authors
    template_name = 'quotes_app/add_author.html'
    form_class = AuthorForm
    success_url = reverse_lazy('quotes_app:main')


@method_decorator(login_required, name='dispatch')
class AddQuoteView(CreateView):
    model = Quotes
    template_name = 'quotes_app/add_quote.html'
    form_class = QuoteForm
    success_url = reverse_lazy('quotes_app:main')


@method_decorator(login_required, name='dispatch')
class AddTagView(CreateView):
    model = Tags
    template_name = 'quotes_app/add_tag.html'
    form_class = CreateTagForm
    success_url = reverse_lazy('quotes_app:main')


@method_decorator(login_required, name='dispatch')
class BindTagView(CreateView):
    model = Tags
    template_name = 'quotes_app/bind_tags.html'
    form_class = BindTagForm
    success_url = reverse_lazy('quotes_app:main')


def sync(request):
    task.delay()
    return redirect('quotes_app:main')

quotes_project/quotes_app/templates/quotes_app/add_author.html
{% extends "quotes_app/base.html" %}

{% block content %}
<div class="container p-4">
    <h2>Create author</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

quotes_project/quotes_app/templates/quotes_app/add_quote.html
{% extends "quotes_app/base.html" %}

{% block content %}
<div class="container p-4">
    <h2>Create quote</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

quotes_project/quotes_app/templates/quotes_app/add_tag.html
{% extends "quotes_app/base.html" %}

{% block content %}
<div class="container p-4">
    <h2>Create tag</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

quotes_project/quotes_app/templates/quotes_app/author.html
{% extends "quotes_app/base.html" %}

{% block content %}
<div class="container p-4">
    <h3>{{ author }}</h3>
    <p>
        <b>Born: </b>
        <span>{{ author.born_date }}</span>
        <span>{{ author.born_location }}</span>
    </p>
    <p><b>Description:</b></p>
    <div>{{ author.description }}</div>
</div>
{% endblock %}

quotes_project/quotes_app/templates/quotes_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <title>Quotes to Scrape</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand link-primary text-primary text-opacity-75" href="{% url 'quotes_app:main' %}">
                <h1><b>Quotes to Scrape</b></h1>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quotes_app:sync' %}" role="button">
                            Sync
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Add
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'quotes_app:add_author' %}">Author</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'quotes_app:add_quote' %}">Quote</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'quotes_app:add_tag' %}">Tag</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'quotes_app:bind_tags' %}">Bind tags</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav mb-2 mb-lg-0 ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Profile
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            {% if user.is_authenticated %}
                            <li>
                                <form method="post" action="{% url 'users:logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item">Logout</button>
                                </form>
                            </li>
                            {% else %}
                            <li>
                                <a class="dropdown-item" href="{% url 'users:signup' %}">Signup</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:login' %}">Signin</a>
                            </li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
{% block content %}{% endblock %}
</body>
</html>

quotes_project/quotes_app/templates/quotes_app/bind_tags.html
{% extends "quotes_app/base.html" %}

{% block content %}
<div class="container p-4">
    <h2>Bind tags to quote</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

quotes_project/quotes_app/templates/quotes_app/quotes_list.html
{% extends "quotes_app/base.html" %}

{% block content %}
<div class="container d-flex justify-content-between">
    <div class="list-group ms-2">
        {% if not quotes %}
        <div class="list-group-item mb-3 border rounded d-flex flex-column">
            Press "Sync" to synchronize data (only for registered users)
            P.S It may take a few minutes to download, just reload page
        </div>
        {% endif %}
        {% for quote in quotes %}
        <div class="list-group-item mb-3 border rounded d-flex flex-column">
            <span class="m-1 h5 fw-normal"><i>{{ quote }}</i></span>
            <span class="m-1">by <b class="text-primary text-opacity-75">{{ quote.author }}</b>
                <a href="{% url 'quotes_app:author' quote.author %}"
            class="link-underline link-primary link-underline-opacity-0 text-opacity-75">(about)</a></span>
            <div class="m-1">Tags:
                {% for tag_name in quote.tags.all %}
                <a class="link-underline link-primary link-underline-opacity-0 text-white bg-primary bg-opacity-50 rounded p-1"
                   href="{% url 'quotes_app:tag' tag_name %}" style="font-size:14px;">{{ tag_name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link{% if not quotes.has_previous %} disabled{% else %} text-primary text-opacity-75{% endif %}"
                       href="{% if quotes.has_previous %}?page={{ quotes.previous_page_number }}{% endif %}">
                        Previous
                    </a>
                </li>
                {% for page in quotes.paginator %}
                <li class="page-item{% if page.number == quotes.number %} active{% endif %}">
                    <a class="page-link{% if page.number == quotes.number %} bg-primary bg-opacity-50 border-primary border-opacity-25{% else %} text-primary text-opacity-75{% endif %}"
                       {% if page.number != quotes.number %}href="?page={{ page.number }}" {% endif %}>
                        {{ page.number }}
                    </a>
                </li>
                {% endfor %}
                <li class="page-item">
                    <a class="page-link{% if not quotes.has_next %} disabled{% else %} text-primary text-opacity-75{% endif %}"
                       href="{% if quotes.has_next %}?page={{ quotes.next_page_number }}{% endif %}">Next</a>
                </li>
            </ul>
        </nav>
    </div>
    <aside class="mx-5">
        <h2 style="white-space: nowrap;">Top Ten tags</h2>
        <ul>
            {% for tag in tags_font|slice:":10" %}
            <li class="d-flex flex-row-reverse">
                <a class="link-underline link-primary link-underline-opacity-0 text-white bg-primary bg-opacity-50 rounded p-1 m-1"
                   href="{% url 'quotes_app:tag' tag.name %}" style="font-size:{{ tag.font }}px;">
                    {{ tag.name }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </aside>
</div>
{% endblock %}